version: '3.9'

services:
  db:
    image: postgres:16
    container_name: buttontrack-db
    environment:
      POSTGRES_DB: buttontrack
      POSTGRES_USER: btuser
      POSTGRES_PASSWORD: btpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: buttontrack-backend
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/buttontrack
      DATABASE_USER: btuser
      DATABASE_PASSWORD: btpass
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./backend/.env:/app/.env

volumes:
  postgres-data:
