ktor:
    application:
        modules:
            - com.buttontrack.ApplicationKt.module
    deployment:
        port: 8080
        host: "0.0.0.0"
        dbUrl: "jdbc:postgresql://localhost:5432/buttontrack_db"
        dbUser: "buttontrack_user"
        dbPassword: "buttontrack_password"