ktor:
    application:
        modules:
            - com.buttontrack.ApplicationKt.module
    deployment:
        port: 8080
        host: "0.0.0.0"
        dbUrl: ${?DB_URL}
        dbUser: ${?DB_USER}
        dbPassword: ${?DB_PASSWORD}
    development: true
